name: build and upload tagged release
on:
  push:
    tags:
      - "v*"

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'
      - name: build
        run: ./make.sh
      - name: version
        run: echo "version=$(./ytarchive -V)" >> $GITHUB_OUTPUT
        id: version
      - name: release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: ${{ steps.version.outputs.version }}
          files: |
            ytarchive_linux_amd64.zip
            ytarchive_windows_amd64.zip
            ytarchive_linux_armv7l.zip
            ytarchive_linux_armv6.zip
            ytarchive_linux_mips.zip
            ytarchive_linux_mipsle.zip
            ytarchive_windows_arm64.zip
            ytarchive_linux_arm64.zip
            ytarchive_macos_arm64.zip
            ytarchive_macos.zip
            SHA2-256SUMS

